version: '3'

services:
  atelier:
    container_name: atelier-api
    image: marcoudi40/atelier-app1:latest
    ports:
      - "8080:8080"
    environment:
      TZ: "America/Sao_Paulo"
      JAVA_TOOL_OPTIONS: "-XX:MaxDirectMemorySize=8M \
        -XX:MaxMetaspaceSize=64M \ 
        -XX:ReservedCodeCacheSize=16M \
        -Xss512K"
