version: '3'

services:
  atelier:
    container_name: atelier-api
    image: marcoudi40/atelier-app1:latest
    ports:
      - "8081:8081"
    environment:
      TZ: "America/Sao_Paulo"
    networks:
        - docker-network
    deploy:
      resources:
        limits:
          memory: 700M
        reservations:
          memory: 700M
    restart: always

networks:
  docker-network:
    driver: bridge
